// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Formation.SE24157303.TestDomain.EFCorePowerTools.Models;

public partial class ClientDbset
{
    public int Id { get; set; }

    public int Age { get; set; }

    public string Nom { get; set; }

    public string Email { get; set; }

    public DateTime DateCreation { get; set; }

    public DateTime DateDerniereModification { get; set; }

    public string UserCreation { get; set; }

    public string UserModification { get; set; }

    public int ClientType { get; set; }

    public int IdentifiantNationale { get; set; }
}