// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Formation.SE24157303.TestDomain.EFCorePowerTools.Models;

public partial class Facture
{
    public int Id { get; set; }

    public int? Numero { get; set; }

    public decimal? Montant { get; set; }
}