// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Formation.SE24157303.TestDomain.EFCorePowerTools.Models;

public partial class SalesDbContext : DbContext
{
    public SalesDbContext(DbContextOptions<SalesDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ClientDbset> ClientDbsets { get; set; }

    public virtual DbSet<Facture> Factures { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ClientDbset>(entity =>
        {
            entity.ToTable("ClientDbset");

            entity.Property(e => e.Email).IsRequired();
            entity.Property(e => e.Nom).IsRequired();
            entity.Property(e => e.UserCreation).IsRequired();
            entity.Property(e => e.UserModification).IsRequired();
        });

        modelBuilder.Entity<Facture>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Facture__3214EC07F41431DD");

            entity.ToTable("Facture");

            entity.Property(e => e.Montant).HasColumnType("decimal(18, 0)");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}